---
abstract: 'Use WebKit to Generate PDFs from HTML (via wkhtmltopdf)'
author:
  - 'Philip Garrett <philip.garrett@icainformatics.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Spec: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDF-WebKit
no_index:
  directory:
    - inc
    - t
recommends:
  XML::LibXML: 1.62
requires:
  IPC::Run: 0
  Moose: 0
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
